### ISSUE TITLE
Генерация отчетов

### ISSUE THREAD

**Issue by w3prog** [w3prog/teacherPlan#12]

**Comment by w3prog** [comment]
Расскажите какие нужно генерировать отчеты помимо печатной версии самого документа?

**Comment by krinkin** [comment]
дано: виды активностей (метод работа, модернизация дисциплин,... ит.д. из плана преподавателя !кроме учебной нагрузки)
требуется: генерировать отчеты по заданному виду активности на заданный период 
- по всей кафедре 
- по заданному преподавателю.
