### ISSUE TITLE
Основные варианты использования приложения?

### ISSUE THREAD

**Issue by w3prog** [w3prog/teacherPlan#2]

**Comment by w3prog** [comment]
Хотелось бы знать каким образом можно использовать данное приложение?

**Comment by krinkin** [comment]
- преподаватель заполняет предполагаемые активности на ближайший год
- преподаватель вносит результаты выполнения плана за прошедший период по каждому виду активностей
- преподаватель генерирует отчеты по самому себе
- администратор генерирует все возможные отчеты

**Comment by w3prog** [comment]
Спасибо за ответ
