### ISSUE TITLE
Создание административного интерфейса для приложения

### ISSUE THREAD

**Issue by w3prog** [w3prog/teacherPlan#7]

**Comment by w3prog** [comment]
Какие роли нужны для редактирования плана преподавателя, подходит ли следующая схема:
Преподаватель;
Управленец или менеджер тоже преподаватель, но может получать различные отчеты;
Администратор права менеджера + доступ в административную панель Django.

**Comment by krinkin** [comment]
Роли:
- преподаватель: редактирует свой план, генерирует отчеты по своим активностям
- администратор: генерирует все доступные отчеты
  
  что такое "доступ в административную панель Django?", какое отношение это имеет к ролям пользователя?

**Comment by w3prog** [comment]
если две роли то никакой, у администратора сайта будет доступ к ней, если 3 роли можно создать миниверсию административной панели сайта с урезанным функционалом, которая будет доступна менеджеру. Спасибо за ответ.
