### ISSUE TITLE
Планирование учебной нагрузки

### ISSUE THREAD

**Issue by w3prog** [w3prog/teacherPlan#8]
Каким способом реализовывать данный функционал?

**Comment by w3prog** [comment]
Нужен ли здесь какой-то специфичный функционал?

**Comment by krinkin** [comment]
Планирование учебной нагрузки заключается в сопоставлении преподавателей с дисциплинами учебного процесса. Эта функция самая низко-приоритетная из всего списка фич. предлагаю ее понизить в приоритете.

**Comment by w3prog** [comment]
Понятно переношу на 3 или 4 дедлайн
